# Generated by Django 3.1.2 on 2020-10-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipments',
            old_name='about',
            new_name='About',
        ),
        migrations.RenameField(
            model_name='equipments',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='equipments',
            old_name='shop',
            new_name='Shop',
        ),
    ]
