# Generated by Django 3.1.2 on 2020-10-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20201023_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='Number',
            field=models.FloatField(default=4, max_length=20),
            preserve_default=False,
        ),
    ]
