# Generated by Django 3.1.2 on 2020-10-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20201023_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='Date',
            field=models.CharField(max_length=100),
        ),
    ]
