# Generated by Django 3.1.2 on 2020-10-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20201023_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='Number',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Price',
            field=models.IntegerField(max_length=20),
        ),
    ]
