# Generated by Django 3.1.2 on 2020-10-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20201026_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='Number',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Price',
            field=models.FloatField(max_length=20),
        ),
    ]
