# Generated by Django 3.1.2 on 2020-10-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20201026_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='Number',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Price',
            field=models.FloatField(),
        ),
    ]
