# Generated by Django 3.1.2 on 2020-10-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20201026_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
